# Cloud Build configuration for staging deployment
# Triggers: Push to main branch or manual trigger
#
# Required substitutions (set in Cloud Build trigger or command):
#   _REGION: GCP region (e.g., us-central1)
#   _SERVICE_NAME: Cloud Run service name
#   _DATABASE_URL: PostgreSQL connection string
#   _AUTH_SECRET: NextAuth secret key
#
# Required APIs:
#   - Cloud Build API
#   - Cloud Run API
#   - Artifact Registry API
#   - Secret Manager API (recommended for secrets)

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: real-state-staging
  _REPOSITORY: real-state

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--build-arg'
      - 'AUTH_SECRET=${_AUTH_SECRET}'
      - '--build-arg'
      - 'NEXTAUTH_URL=https://${_SERVICE_NAME}-${PROJECT_ID}.${_REGION}.run.app'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL_STAGING:latest,AUTH_SECRET=AUTH_SECRET:latest'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
